# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exelfile',
            name='date',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exelfile',
            name='file',
            field=models.FileField(upload_to='uploads/exels/'),
        ),
    ]
