# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 07:33
from __future__ import unicode_literals

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180102_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/algorithms/', validators=[dashboard.validators.validate_algorithm_file_extension])),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
