# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 07:49
from __future__ import unicode_literals

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180104_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfile',
            name='file',
            field=models.FileField(upload_to='uploads/input-files/', validators=[dashboard.validators.validate_input_file_extension]),
        ),
    ]
