# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180104_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='title',
            field=models.CharField(default='Algorithm', max_length=255),
        ),
        migrations.AlterField(
            model_name='inputfile',
            name='title',
            field=models.CharField(default='File', max_length=255),
        ),
    ]
