# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180104_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptiom', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='algorithm',
            name='project',
            field=models.ManyToManyField(to='dashboard.Project'),
        ),
        migrations.AddField(
            model_name='inputfile',
            name='project',
            field=models.ManyToManyField(to='dashboard.Project'),
        ),
    ]
