# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180104_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
