# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180104_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputfile',
            name='project',
        ),
        migrations.AddField(
            model_name='inputfile',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Project'),
            preserve_default=False,
        ),
    ]
