# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180104_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inputfile',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
