# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_result_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/result/'),
        ),
        migrations.AlterField(
            model_name='result',
            name='file_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.InputFile'),
        ),
    ]
