# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('short_text', models.CharField(max_length=250, verbose_name='Short desc')),
                ('text', models.TextField(verbose_name='Full desc')),
                ('date', models.DateField()),
            ],
        ),
    ]
